### ISSUE TITLE
Add Monterey to supported releases

### ISSUE THREAD

**Issue by lockefox** [wayofdev/ansible-role-dock#5]
Followed from: https://github.com/geerlingguy/ansible-collection-mac/issues/42

Unable to install from ansible-galaxy:
```bash
ansible-galaxy install wayofdev.dock          
Starting galaxy role install process
- downloading role 'dock', owned by wayofdev
[WARNING]: - wayofdev.dock was NOT installed successfully: - sorry, wayofdev.dock was not found on https://galaxy.ansible.com/api/.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

OS: Monterey 12.4
Machine: MacBook Pro (2019) Intel

**Comment by lotyp** [comment]
Thanks for reporting, will check. Right now I didn't find in galaxy Monterey tag, probably will need to report to ansible, and temporary add "all" instead of tags

**Comment by lotyp** [comment]
@lockefox please test with v2.0.0 / later or master branch. Should be resolved by now.

Also, please be aware, that variables have changed, as I've implemented ansible best practices.
