### ISSUE TITLE
Fails over SSH unless environment variable adds homebrew to path

### ISSUE THREAD

**Issue by acgourley** [wayofdev/ansible-role-dock#8]
If you're trying to use this package over SSH, it will fail saying `stderr: '/bin/sh: dockutil: command not found'` and the following is needed to add homebrew into the default path. 

So I suppose the fix is either finding a way around needing this, or adding it into the docs. 

```
    - role: lotyp.dock
      environment: 
        - PATH: '/usr/local/bin:/usr/local/sbin:/opt/homebrew/bin'
```

**Comment by lotyp** [comment]
@acgourley Thanks for your reports! I'm already checking all your issues.

**Comment by lotyp** [comment]
v2.x.x is now running tests over molecule, so I've tested over ssh and did some tweaks.

Added to documentation, note about, PATH:

btw, better to extend, not overwrite it:

```
  environment:
    - PATH: "/usr/local/bin:/usr/local/sbin:/opt/homebrew/bin:{{ ansible_env.PATH }}"
```
